### PR TITLE
lets us only connect to some channels in bitfinex WSS constructor

### PR DESCRIPTION
**Pull request by terramars**
also bump the timeout and make default log level = logging.INFO

### CODE REVIEW

**Comment by nlsdfnbch** [comment]
Hey there, and thanks for your PR!

1.  Addition of `log.setLevel(logging.INFO)`
Setting the logging level isn't done in the module, because you should do this in the program code, not the library.

2. Restriction of endpoints to subscribe to
Why do you want to limit the endpoints ? The cost for subscribing to all endpoints is minimal and shouldn't reflect on performance (please do inform me if this is not the case!)

3. Addition of kwargs `freq` and `prec` in `book()`
You've added the keywords  when calling `_subscribe()` in the method `book` - this is unnecessary, as it's the default for the book endpoint of the Bitfinex API. I believe you wanted to make it more explicit, to readers of the code (which is a good thing, no doubt) - however, if the default for the API changes, this would result in unexpected behaviour to users who do not read the code.

**Comment by terramars** [comment]
Hey! Thanks for your awesome library. I am using it in my project and it's a huge help.

I don't feel strongly about any of these changes, I mostly sent the PR as an excuse to open a conversation particularly regarding the WSS stability.  I'm writing order books using them using the OrderBook library (just done with GDAX and Bitfinex so far) - my main reason for limiting the endpoints is because I plan to connect to several WSS at once and want to restrict to only the ones I'm using.  I wouldn't have bothered, but I had problems with the Bitfinex raw book - I haven't been able to get an accurate position out of it, I think there may be dropped messages, or something undocumented like trades changing orders that aren't reflected in the book feed.

I think it's more useful on GDAX, it's just helpful to not get pairs you're not trading.  I have changes for that on my branch but they are very recent.

One thing I've been wondering, your V2 development appears to not include any WSS code.  What's up with that?  Are there any pressing issues with that code that would be useful to have a go at?  One thing I noticed is the command queue doesn't actually work to restart the client, which I assume is a threading issue, but I have no idea how to fix it or if it's even a real problem.

**Comment by nlsdfnbch** [comment]
Glad it's of use to you!

Yes, version `2.0` doesn't include Websockets - _yet_. The current implementation of the websockets was experimental, as the code was taken from my standalone websocket client projects. They haven't been updated, and literally none of the (much needed bugfixes) were made since they were introduced.

The only reason Websockets arent in 2.0 yet is because I need to figure out reliable tests for them, and implementing the REST APIs first is more straight-forward (and also, BitEx was meant to be REST-only when I started out, so I prioritized those APIs). Luckily, Implementing them shouldn't be too complicated, as the tests are now more or less the same for all APIs - the biggest obstacle stopping me from progressing is available time on my end, unfortunately.

For Bitfinex specifically, you should perhaps check out my `btfxwss` library - it's a rewrite of most of the code, and I believe it handles itself better than the code used in `Bitex` - for one, the terrible controller thread implementation got axed (bane of my life, I tell you). It should be more stable, and doesn't do any automatic subscribing.

And please, no need to find excuses to start discussions on anything - I'm always happy to answer any questions or simply engage in a constructive discussion about any part of this project!

**Comment by terramars** [comment]
Right on.  I'll check out that version!  I think my current implementation
is more or less stable - I get around the restart issue by just hard
rebooting the socket feed if it doesn't get any data for a length of time
(stop then call the constructor again, which works fine tbh.  The GDAX one
also seems more or less stable, I'm not sure I'd do it differently if I
were writing it from scratch.

I also started out doing basically what you're doing with the REST apis,
but they are so insufficient for doing anything substantial!  I don't trust
the data at all, for actually executing orders.  Websocket is unreliable
enough as is, combine that with those really low rate limits and you're
just asking for problems.

**Comment by nlsdfnbch** [comment]
Yes, that's true - trading on REST is rather risky. When I started out the framework was meant for data gathering only, so we didn't care much about real-time data; we only needed it at regular intervals.

Also, it's not really helping that there's so many different protocols used for the Websocket APIs (WAMP, Pusher, Socket.IO, etc), so it's a terribly long list of depencies to add to the project. Of course all of them use some form of websocket under the hood, but writing a unified wrapper for all of them is a lot of, some might argue unnecessary, work.

**Comment by terramars** [comment]
Yeah, dependencies are cheap though. It's totally worth it for the
convenience of interoperability.

On Jul 22, 2017 12:01 AM, "Nils" <notifications@github.com> wrote:

Yes, that's true - trading on REST is rather risky. When I started out the
framework was meant for data gathering only, so we didn't care much about
real-time data; we only needed it at regular intervals.

Also, it's not really helping that there's so many different protocols used
for the Websocket APIs (WAMP, Pusher, Socket.IO, etc), so it's a terribly
long list of depencies to add to the project. Of course all of them use
some form of websocket under the hood, but writing a unified wrapper for
all of them is a lot of, some might argue unnecessary, work.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nlsdfnbch/bitex/pull/67#issuecomment-317161739>, or mute
the thread

**Pull request closed without merging**
